audio:
  input_file: audio/file.wav
  output_file: output/output
  output_format: txt

model:
  name: base
  language: auto

whisper:
  temperature: 0
  compression_ratio_threshold: 2.4
  logprob_threshold: -1.0
  no_speech_threshold: 0.6
  fp16: True

diarization:
  enabled: true
  frame_length: 0.025  # 25 ms
  hop_length: 0.010  # 10 ms
  energy_threshold: 1.5  # Adjust this value to change sensitivity
  min_silence_duration: 0.5  # Minimum duration of silence to be considered a pause (in seconds)
  min_speech_duration: 0.5  # Minimum duration of speech to be considered a segment (in seconds)

translation:
  enabled: false
  target_language: en

preprocess:
  enabled: false
  noise_reduction: true
  normalize: true
  output_file: preprocessed/audio.wav